### ISSUE TITLE
ToucanAuthorizationFilter consider stopping on a Challenge Result

### ISSUE THREAD

**Issue by vcsjones** [EntropyZero/Toucan#5]
When the action filter goes through each `LoadAndAuthorizeResourceAttribute`, failure to authorize results in the context's result being a ChallengeResult.

However, the action filter continues to go through all of the attributes, anyway. It may be desirable to change this:

```
context.Result = new ChallengeResult();
```

to 

```
context.Result = new ChallengeResult();
break;
```

To avoid authorizing all of the models even when we know the result will be a failure.

What isn't clear to me is if this is intentional or not.

**Comment by philmcmillan** [comment]
It's not really intentional in the sense that any failure should prevent controller from acting, so continuing through all of the attributes is needlessly expensive. I'll add the break statement. 👍
